//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub mod prelude;
pub mod entity_linked;
pub mod asset;
pub mod permissions;
pub mod role;
pub mod roles_permissions;
pub mod test_role;
pub mod test_user;
pub mod user;
pub mod user_roles;
