//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "test_role")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::test_user::Entity")]
    TestUser,
}

impl Related<super::test_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TestUser.def()
    }
}

impl Related<super::permissions::Entity> for Entity {
    fn to() -> RelationDef {
        super::roles_permissions::Relation::Permissions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::roles_permissions::Relation::TestRole.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
